version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: port-scanner-db
    environment:
      POSTGRES_DB: port_scanner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - port-scanner-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  port-scanner-app:
    build: .
    container_name: port-scanner-app
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Istanbul
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/port_scanner_db
      - FLASK_ENV=development
    volumes:
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - port-scanner-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  port-scanner-network:
    driver: bridge 